# randomization params
random_state: 123

# data selection params
dummy_cols: ["type", "quality_category"]
input_cols: ["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol", "white"]
target_col: "High"

# train test params
test_size: 0.3

# general kfold params

k: 10
k-shuffle: True

# general crossvalidation params

n_iter: 25
scoring: f1
error_score: 0
verbose: 1
n_jobs: -1


# knn crossvalidation params

knn_n_neighbors: [1, 3, 5, 7, 9, 11]

# xgb crossvalidation params

colsample_bytree: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
subsample: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
xgb_max_depth: [3, 4, 5, 6, 7, 8, 9]
xgb_min_child_weight: [1, 2, 3, 4]


